data:
  batch_size: 64
  dataset:
    name: PolSFDataset
    trainpath: ../../datasets/SAN_FRANCISCO_ALOS2
  transform: LogAmplitude
  img_size: 64
  img_stride: 64
  num_workers: 4
  valid_ratio: 0.15
  test_ratio: 0.15
logging:
  logdir: ./logs
  wandb:
    entity: equivariant_cvnn
    project: polsf_test
model:
  activation: modReLU
  channels_ratio: 16
  downsampling: StridedConv
  upsampling: Upsample
  dropout : 0.1
  normalization: 
    method: BatchNorm
    track_running_stats: false
  num_layers: 2
nepochs: 300
optim:
  algo: AdamW
  params:
    lr: 0.005
    weight_decay: 0.0005
scheduler:
  algo: StepLR
  params:
    step_size: 5
    gamma: 0.9
pretrained: false
world_size: 4
dtype: complex64
